# Rio Configuration File
# Documentation: https://raphamorim.io/rio/docs/

theme = "noctalia"

[window]
opacity = 0.85
blur = true
decorations = "Buttonless"

[fonts]
size = 15.0
family = "FantasqueSansM Nerd Font"

[fonts.regular]
family = "FantasqueSansM Nerd Font"
style = "normal"
weight = 700

[effects]
trail-cursor = true

