%hidden MODULE_NAME="ctp_memory"

set -gq @catppuccin_ctp_memory_icon " "
set -gq @catppuccin_ctp_memory_color "#{E:@thm_sky}"
set -gq @catppuccin_ctp_memory_text "#{ram_percentage}"

source -F "#{d:current_file}/../utils/status_module.conf"
