%hidden MODULE_NAME="ctp_cpu"

set -gq @catppuccin_ctp_cpu_icon " "
set -gq @catppuccin_ctp_cpu_color "#{E:@thm_peach}"
set -gq @catppuccin_ctp_cpu_text "#{cpu_percentage}"

source -F "#{d:current_file}/../utils/status_module.conf"
